name: Winecamp
favicon: null
layout_spectrum: 0.08864
typography_spectrum: 0.88406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#806c4f'
    - '#c36b3c'
    - '#c58d4f'
    - '#9d4528'
  brandStrength: 0.5104711407329887
  lightness: 0.7767507983371615
  saturation: 0.75
  rhythmicContrast: 0.8519515872467309
purpose: []
